@echo off
echo Running CPU Experiment...
call ..\cpu_version\run_cpu.bat --script train_on_input2_cpu.py
echo Running GPU Experiment...
call ..\gpu_version\run_gpu.bat --script train_on_input2.py
echo Running Comparison...
python compare.py
echo Done.
